#!/bin/sh
if [ $# -ne 1 ]
then
	echo "usage: $0 <outputfile>"
	exit 1
fi
(
cat <<EOF
/*
 *
 * File generated by $0
 *
 */
EOF
echo "#define MAJOR 0"
echo "#define MINOR 3"
date "+#define BUILD \"%Y%m%d%H%M\""
) > $1
